name: Build Development Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: adopt
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Remove dev and sources jars
        run: |
          rm ./build/libs/*-dev.jar
          rm ./build/libs/*-sources.jar
        
      - name: Publish Development Build
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: development-build
          prerelease: false
          title: Development Build
          files: ./build/libs/*.jar
